"""add_receta_personalizada_to_detalle_cotizacion

Revision ID: 1068f2fa6502
Revises: d862d3fbe748
Create Date: 2026-07-25 02:10:32.103436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1068f2fa6502'
down_revision: Union[str, None] = 'd862d3fbe748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_cotizacion', sa.Column('receta_personalizada', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalle_cotizacion', 'receta_personalizada')
    # ### end Alembic commands ###
