"""intelligent_quotes

Revision ID: 530ad3bcdb72
Revises: 614939ee4000
Create Date: 2026-07-15 11:08:21.023730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '530ad3bcdb72'
down_revision: Union[str, None] = '614939ee4000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cama_historica_atributos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('tiene_tapiceria', sa.Boolean(), nullable=False),
    sa.Column('tiene_nocheros', sa.Boolean(), nullable=False),
    sa.Column('tiene_espejo', sa.Boolean(), nullable=False),
    sa.Column('tiene_luces', sa.Boolean(), nullable=False),
    sa.Column('tipo_patas', sa.String(length=50), nullable=True),
    sa.Column('estilo_general', sa.String(length=50), nullable=True),
    sa.Column('vector_similitud', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id')
    )
    op.create_index(op.f('ix_cama_historica_atributos_id'), 'cama_historica_atributos', ['id'], unique=False)
    
    op.create_table('cotizacion_analisis_ia',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cotizacion_id', sa.BigInteger(), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=False),
    sa.Column('tipo_mueble', sa.String(length=50), nullable=False),
    sa.Column('familia_probable', sa.String(length=50), nullable=True),
    sa.Column('tiene_tapiceria', sa.Boolean(), nullable=False),
    sa.Column('tiene_nocheros', sa.Boolean(), nullable=False),
    sa.Column('tiene_espejo', sa.Boolean(), nullable=False),
    sa.Column('tiene_luces', sa.Boolean(), nullable=False),
    sa.Column('tipo_patas', sa.String(length=50), nullable=True),
    sa.Column('estilo_general', sa.String(length=50), nullable=True),
    sa.Column('nivel_confianza', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizacion.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizacion_analisis_ia_id'), 'cotizacion_analisis_ia', ['id'], unique=False)
    
    op.create_table('material_sinonimo',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('sinonimo', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sinonimo')
    )
    op.create_index(op.f('ix_material_sinonimo_id'), 'material_sinonimo', ['id'], unique=False)
    
    op.create_table('cotizacion_detalle_material',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('detalle_cotizacion_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.Column('cantidad_base', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('cantidad_calculada', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('tipo_escala', sa.String(length=20), nullable=False),
    sa.Column('distancia_pauta_cm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('tornillos_por_pieza', sa.Integer(), nullable=True),
    sa.Column('formula_personalizada', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['detalle_cotizacion_id'], ['detalle_cotizacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizacion_detalle_material_id'), 'cotizacion_detalle_material', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cotizacion_detalle_material_id'), table_name='cotizacion_detalle_material')
    op.drop_table('cotizacion_detalle_material')
    op.drop_index(op.f('ix_material_sinonimo_id'), table_name='material_sinonimo')
    op.drop_table('material_sinonimo')
    op.drop_index(op.f('ix_cotizacion_analisis_ia_id'), table_name='cotizacion_analisis_ia')
    op.drop_table('cotizacion_analisis_ia')
    op.drop_index(op.f('ix_cama_historica_atributos_id'), table_name='cama_historica_atributos')
    op.drop_table('cama_historica_atributos')
    # ### end Alembic commands ###
