"""crear_detalle_cotizacion

Revision ID: 8d0e6ee658f6
Revises: 
Create Date: 2026-06-15 20:03:48.950812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0e6ee658f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_cotizacion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cotizacion_id', sa.BigInteger(), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('alto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ancho', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('largo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('costo_materiales', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('costo_mano_obra', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('costo_gastos', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('costo_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_cotizacion_id'), 'detalle_cotizacion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_cotizacion_id'), table_name='detalle_cotizacion')
    op.drop_table('detalle_cotizacion')
    # ### end Alembic commands ###
