"""add_cost_fields_to_politica_seccion

Revision ID: c510a2c6c2df
Revises: f1dcdf808d98
Create Date: 2026-07-24 18:21:27.163262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c510a2c6c2df'
down_revision: Union[str, None] = 'f1dcdf808d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('politica_seccion', sa.Column('costo_fabricacion', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('politica_seccion', sa.Column('pct_trabajadores', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('politica_seccion', sa.Column('pct_negocio', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('politica_seccion', 'pct_negocio')
    op.drop_column('politica_seccion', 'pct_trabajadores')
    op.drop_column('politica_seccion', 'costo_fabricacion')
    # ### end Alembic commands ###
