"""add_costo_produccion_seccion_table

Revision ID: d862d3fbe748
Revises: c510a2c6c2df
Create Date: 2026-07-24 19:27:50.611257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd862d3fbe748'
down_revision: Union[str, None] = 'c510a2c6c2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costo_produccion_seccion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('seccion_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('costo_base', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion_producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costo_produccion_seccion_id'), 'costo_produccion_seccion', ['id'], unique=False)
    op.create_index(op.f('ix_costo_produccion_seccion_seccion_id'), 'costo_produccion_seccion', ['seccion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_costo_produccion_seccion_seccion_id'), table_name='costo_produccion_seccion')
    op.drop_index(op.f('ix_costo_produccion_seccion_id'), table_name='costo_produccion_seccion')
    op.drop_table('costo_produccion_seccion')
    # ### end Alembic commands ###
