"""add seccion_producto, elemento_seccion and politica_seccion

Revision ID: f1dcdf808d98
Revises: c1f2e3d4e5f7
Create Date: 2026-07-23 11:40:00.382985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1dcdf808d98'
down_revision: Union[str, None] = 'c1f2e3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seccion_producto',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('producto_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seccion_producto_id'), 'seccion_producto', ['id'], unique=False)
    op.create_index(op.f('ix_seccion_producto_producto_id'), 'seccion_producto', ['producto_id'], unique=False)
    op.create_table('elemento_seccion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('seccion_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre_insumo_original', sa.String(length=150), nullable=False),
    sa.Column('material_id_normalizado', sa.BigInteger(), nullable=True),
    sa.Column('estado_resolucion', sa.String(length=30), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('costo_subtotal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id_normalizado'], ['material.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion_producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elemento_seccion_id'), 'elemento_seccion', ['id'], unique=False)
    op.create_index(op.f('ix_elemento_seccion_seccion_id'), 'elemento_seccion', ['seccion_id'], unique=False)
    op.create_table('politica_seccion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('seccion_id', sa.BigInteger(), nullable=False),
    sa.Column('mano_obra_base', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('pct_liquidacion_mo', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pct_gastos_seccion', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion_producto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seccion_id')
    )
    op.create_index(op.f('ix_politica_seccion_id'), 'politica_seccion', ['id'], unique=False)
    op.drop_table('cotizacion_material_ajuste')
    op.drop_constraint('area_nombre_key', 'area', type_='unique')
    op.create_index(op.f('ix_area_id'), 'area', ['id'], unique=False)
    op.drop_table_comment(
        'area',
        existing_comment='Áreas físicas o lógicas de producción.',
        schema=None
    )
    op.drop_constraint('cargo_nombre_key', 'cargo', type_='unique')
    op.create_index(op.f('ix_cargo_id'), 'cargo', ['id'], unique=False)
    op.drop_table_comment(
        'cargo',
        existing_comment='Cargos ocupados por los empleados.',
        schema=None
    )
    op.alter_column('cliente', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('cliente_id_seq'::regclass)"))
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.drop_table_comment(
        'cliente',
        existing_comment='Registro de clientes.',
        schema=None
    )
    op.drop_index('idx_compra_moneda', table_name='compra')
    op.drop_index('idx_compra_proveedor', table_name='compra')
    op.create_index(op.f('ix_compra_id'), 'compra', ['id'], unique=False)
    op.drop_constraint('compra_moneda_id_fkey', 'compra', type_='foreignkey')
    op.drop_constraint('compra_proveedor_id_fkey', 'compra', type_='foreignkey')
    op.create_foreign_key(None, 'compra', 'proveedor', ['proveedor_id'], ['id'])
    op.create_foreign_key(None, 'compra', 'moneda', ['moneda_id'], ['id'])
    op.drop_table_comment(
        'compra',
        existing_comment='Abastecimiento con proveedores.',
        schema=None
    )
    op.drop_index('idx_consumo_etapa', table_name='consumo_material')
    op.drop_index('idx_consumo_material_fk', table_name='consumo_material')
    op.create_index(op.f('ix_consumo_material_id'), 'consumo_material', ['id'], unique=False)
    op.drop_constraint('consumo_material_material_id_fkey', 'consumo_material', type_='foreignkey')
    op.create_foreign_key(None, 'consumo_material', 'material', ['material_id'], ['id'])
    op.drop_table_comment(
        'consumo_material',
        existing_comment='Descarga de materiales vinculados a una etapa.',
        schema=None
    )
    op.create_index(op.f('ix_costo_produccion_id'), 'costo_produccion', ['id'], unique=False)
    op.drop_table_comment(
        'costo_produccion',
        existing_comment='Consolidado financiero del costo de manufactura.',
        schema=None
    )
    op.drop_index('idx_cotizacion_cliente', table_name='cotizacion')
    op.create_index(op.f('ix_cotizacion_id'), 'cotizacion', ['id'], unique=False)
    op.drop_constraint('cotizacion_cliente_id_fkey', 'cotizacion', type_='foreignkey')
    op.create_foreign_key(None, 'cotizacion', 'cliente', ['cliente_id'], ['id'])
    op.drop_table_comment(
        'cotizacion',
        existing_comment='Propuesta económica entregada al cliente.',
        schema=None
    )
    op.drop_index('idx_detalle_compra_compra', table_name='detalle_compra')
    op.drop_index('idx_detalle_compra_material', table_name='detalle_compra')
    op.create_index(op.f('ix_detalle_compra_id'), 'detalle_compra', ['id'], unique=False)
    op.drop_constraint('detalle_compra_material_id_fkey', 'detalle_compra', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_compra', 'material', ['material_id'], ['id'])
    op.drop_table_comment(
        'detalle_compra',
        existing_comment='Renglones de materiales adquiridos.',
        schema=None
    )
    op.drop_index('idx_detalle_pedido_pedido', table_name='detalle_pedido')
    op.drop_index('idx_detalle_pedido_producto', table_name='detalle_pedido')
    op.create_index(op.f('ix_detalle_pedido_id'), 'detalle_pedido', ['id'], unique=False)
    op.drop_constraint('detalle_pedido_producto_id_fkey', 'detalle_pedido', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_pedido', 'producto', ['producto_id'], ['id'])
    op.drop_table_comment(
        'detalle_pedido',
        existing_comment='Renglones del pedido con configuración personalizada.',
        schema=None
    )
    op.drop_index('idx_detalle_venta_producto', table_name='detalle_venta')
    op.drop_index('idx_detalle_venta_venta', table_name='detalle_venta')
    op.create_index(op.f('ix_detalle_venta_id'), 'detalle_venta', ['id'], unique=False)
    op.drop_table_comment(
        'detalle_venta',
        existing_comment='Líneas de los productos en la venta.',
        schema=None
    )
    op.drop_index('idx_empleado_cargo', table_name='empleado')
    op.create_index(op.f('ix_empleado_id'), 'empleado', ['id'], unique=False)
    op.drop_constraint('empleado_cargo_id_fkey', 'empleado', type_='foreignkey')
    op.create_foreign_key(None, 'empleado', 'cargo', ['cargo_id'], ['id'])
    op.drop_table_comment(
        'empleado',
        existing_comment='Personal de la empresa.',
        schema=None
    )
    op.create_index(op.f('ix_envio_id'), 'envio', ['id'], unique=False)
    op.drop_index('idx_etapa_area', table_name='etapa_produccion')
    op.drop_index('idx_etapa_empleado', table_name='etapa_produccion')
    op.drop_index('idx_etapa_estado', table_name='etapa_produccion')
    op.drop_index('idx_etapa_orden', table_name='etapa_produccion')
    op.create_index(op.f('ix_etapa_produccion_id'), 'etapa_produccion', ['id'], unique=False)
    op.drop_constraint('etapa_produccion_empleado_responsable_id_fkey', 'etapa_produccion', type_='foreignkey')
    op.drop_constraint('etapa_produccion_area_id_fkey', 'etapa_produccion', type_='foreignkey')
    op.create_foreign_key(None, 'etapa_produccion', 'empleado', ['empleado_responsable_id'], ['id'])
    op.create_foreign_key(None, 'etapa_produccion', 'area', ['area_id'], ['id'])
    op.drop_table_comment(
        'etapa_produccion',
        existing_comment='Seguimiento por áreas y encargados de producción.',
        schema=None
    )
    op.alter_column('gasto', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_gasto_moneda', table_name='gasto')
    op.drop_index('idx_gasto_tipo', table_name='gasto')
    op.create_index(op.f('ix_gasto_id'), 'gasto', ['id'], unique=False)
    op.drop_table_comment(
        'gasto',
        existing_comment='Registro de egresos operativos.',
        schema=None
    )
    op.alter_column('inventario', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_inventario_material', table_name='inventario')
    op.drop_index('idx_inventario_ubicacion', table_name='inventario')
    op.drop_constraint('inventario_material_id_ubicacion_id_key', 'inventario', type_='unique')
    op.create_index(op.f('ix_inventario_id'), 'inventario', ['id'], unique=False)
    op.drop_table_comment(
        'inventario',
        existing_comment='Existencias actuales por ubicación.',
        schema=None
    )
    op.drop_index('idx_mano_obra_empleado', table_name='mano_obra')
    op.drop_index('idx_mano_obra_etapa', table_name='mano_obra')
    op.create_index(op.f('ix_mano_obra_id'), 'mano_obra', ['id'], unique=False)
    op.drop_constraint('mano_obra_empleado_id_fkey', 'mano_obra', type_='foreignkey')
    op.create_foreign_key(None, 'mano_obra', 'empleado', ['empleado_id'], ['id'])
    op.drop_table_comment(
        'mano_obra',
        existing_comment='Costos directos por labor de un empleado.',
        schema=None
    )
    op.drop_index('idx_material_unidad', table_name='material')
    op.create_index(op.f('ix_material_id'), 'material', ['id'], unique=False)
    op.drop_constraint('material_unidad_medida_id_fkey', 'material', type_='foreignkey')
    op.create_foreign_key(None, 'material', 'unidad_medida', ['unidad_medida_id'], ['id'])
    op.drop_table_comment(
        'material',
        existing_comment='Materia prima e insumos.',
        schema=None
    )
    op.drop_constraint('moneda_codigo_key', 'moneda', type_='unique')
    op.drop_constraint('moneda_nombre_key', 'moneda', type_='unique')
    op.create_index(op.f('ix_moneda_id'), 'moneda', ['id'], unique=False)
    op.drop_table_comment(
        'moneda',
        existing_comment='Catálogo de monedas (COP, USD, VES).',
        schema=None
    )
    op.alter_column('movimiento_inventario', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('movimiento_inventario', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('idx_movimiento_fecha', table_name='movimiento_inventario')
    op.drop_index('idx_movimiento_material', table_name='movimiento_inventario')
    op.drop_index('idx_movimiento_ubicacion', table_name='movimiento_inventario')
    op.create_index(op.f('ix_movimiento_inventario_id'), 'movimiento_inventario', ['id'], unique=False)
    op.drop_table_comment(
        'movimiento_inventario',
        existing_comment='Kardex/Historial de entradas y salidas.',
        schema=None
    )
    op.drop_index('idx_orden_produccion_estado', table_name='orden_produccion')
    op.create_index(op.f('ix_orden_produccion_id'), 'orden_produccion', ['id'], unique=False)
    op.drop_constraint('orden_produccion_detalle_pedido_id_fkey', 'orden_produccion', type_='foreignkey')
    op.create_foreign_key(None, 'orden_produccion', 'detalle_pedido', ['detalle_pedido_id'], ['id'])
    op.drop_table_comment(
        'orden_produccion',
        existing_comment='Orden fabricada por detalle específico de pedido.',
        schema=None
    )
    op.drop_index('idx_pago_fecha', table_name='pago')
    op.drop_index('idx_pago_moneda', table_name='pago')
    op.drop_index('idx_pago_venta', table_name='pago')
    op.create_index(op.f('ix_pago_id'), 'pago', ['id'], unique=False)
    op.drop_table_comment(
        'pago',
        existing_comment='Abonos y pagos de ventas.',
        schema=None
    )
    op.drop_index('idx_pedido_cliente', table_name='pedido')
    op.drop_index('idx_pedido_estado', table_name='pedido')
    op.create_index(op.f('ix_pedido_id'), 'pedido', ['id'], unique=False)
    op.drop_constraint('pedido_cotizacion_id_fkey', 'pedido', type_='foreignkey')
    op.drop_constraint('pedido_cliente_id_fkey', 'pedido', type_='foreignkey')
    op.create_foreign_key(None, 'pedido', 'cliente', ['cliente_id'], ['id'])
    op.create_foreign_key(None, 'pedido', 'cotizacion', ['cotizacion_id'], ['id'])
    op.drop_table_comment(
        'pedido',
        existing_comment='Solicitud en firme aceptada por el cliente.',
        schema=None
    )
    op.alter_column('producto', 'ancho_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Ancho de referencia para calcular escalado (metros).',
               existing_nullable=True,
               existing_server_default=sa.text('1.60'))
    op.alter_column('producto', 'largo_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Largo de referencia para calcular escalado (metros).',
               existing_nullable=True,
               existing_server_default=sa.text('1.90'))
    op.alter_column('producto', 'alto_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Alto de referencia para calcular escalado (metros), opcional.',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.drop_index('idx_producto_tipo', table_name='producto')
    op.drop_constraint('producto_codigo_key', 'producto', type_='unique')
    op.create_index(op.f('ix_producto_id'), 'producto', ['id'], unique=False)
    op.drop_constraint('producto_tipo_producto_id_fkey', 'producto', type_='foreignkey')
    op.create_foreign_key(None, 'producto', 'tipo_producto', ['tipo_producto_id'], ['id'])
    op.drop_table_comment(
        'producto',
        existing_comment='Catálogo de artículos base.',
        schema=None
    )
    op.alter_column('producto_material', 'tipo_escala',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='FIJO=no cambia | LINEAL=escala con largo | AREA=escala con área | ESPACIADO=perímetro/pauta | POR_RANGO=saltos discretos | FORMULA=expresión personalizada',
               existing_nullable=False)
    op.alter_column('producto_material', 'condicion_activacion',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='JSON: {"campo":"nuevo_largo","op":">","valor":2.0}. Si no se cumple, la cantidad se fuerza a 0.',
               existing_nullable=True)
    op.alter_column('producto_material', 'rangos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment=None,
               existing_comment='JSON para POR_RANGO: [{"max":1.8,"cantidad":2},{"max":2.2,"cantidad":4}].',
               existing_nullable=True)
    op.drop_index('idx_pm_material', table_name='producto_material')
    op.drop_index('idx_pm_producto', table_name='producto_material')
    op.create_index(op.f('ix_producto_material_id'), 'producto_material', ['id'], unique=False)
    op.drop_table_comment(
        'producto_material',
        existing_comment='Receta paramétrica: relaciona cada producto con sus materiales y define cómo escala la cantidad cuando cambian las dimensiones.',
        schema=None
    )
    op.create_index(op.f('ix_proveedor_id'), 'proveedor', ['id'], unique=False)
    op.drop_table_comment(
        'proveedor',
        existing_comment='Entidades que proveen materiales.',
        schema=None
    )
    op.drop_constraint('rol_nombre_key', 'rol', type_='unique')
    op.create_index(op.f('ix_rol_id'), 'rol', ['id'], unique=False)
    op.drop_table_comment(
        'rol',
        existing_comment='Roles del sistema para control de acceso.',
        schema=None
    )
    op.alter_column('tasa_cambio', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_tasa_cambio_destino', table_name='tasa_cambio')
    op.drop_index('idx_tasa_cambio_origen', table_name='tasa_cambio')
    op.drop_constraint('tasa_cambio_moneda_origen_id_moneda_destino_id_fecha_key', 'tasa_cambio', type_='unique')
    op.create_index(op.f('ix_tasa_cambio_id'), 'tasa_cambio', ['id'], unique=False)
    op.drop_table_comment(
        'tasa_cambio',
        existing_comment='Histórico de tasas de conversión.',
        schema=None
    )
    op.create_index(op.f('ix_tipo_gasto_id'), 'tipo_gasto', ['id'], unique=False)
    op.drop_table_comment(
        'tipo_gasto',
        existing_comment='Categorización de los gastos operativos.',
        schema=None
    )
    op.drop_constraint('tipo_producto_nombre_key', 'tipo_producto', type_='unique')
    op.create_index(op.f('ix_tipo_producto_id'), 'tipo_producto', ['id'], unique=False)
    op.drop_table_comment(
        'tipo_producto',
        existing_comment='Clasificación principal de los productos.',
        schema=None
    )
    op.drop_constraint('ubicacion_nombre_key', 'ubicacion', type_='unique')
    op.create_index(op.f('ix_ubicacion_id'), 'ubicacion', ['id'], unique=False)
    op.drop_table_comment(
        'ubicacion',
        existing_comment='Ubicaciones físicas para almacenar inventario.',
        schema=None
    )
    op.drop_constraint('unidad_medida_nombre_key', 'unidad_medida', type_='unique')
    op.create_index(op.f('ix_unidad_medida_id'), 'unidad_medida', ['id'], unique=False)
    op.drop_table_comment(
        'unidad_medida',
        existing_comment='Unidades de medida para los materiales e insumos.',
        schema=None
    )
    op.alter_column('usuario', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('usuario_id_seq'::regclass)"))
    op.alter_column('usuario', 'empleado_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('usuario', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('usuario', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_usuario_empleado', table_name='usuario')
    op.drop_constraint('usuario_empleado_id_key', 'usuario', type_='unique')
    op.drop_constraint('usuario_nombre_usuario_key', 'usuario', type_='unique')
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_nombre_usuario'), 'usuario', ['nombre_usuario'], unique=True)
    op.drop_constraint('fk_usuario_empleado', 'usuario', type_='foreignkey')
    op.drop_table_comment(
        'usuario',
        existing_comment='Usuarios que acceden al sistema.',
        schema=None
    )
    op.alter_column('usuario_rol', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('usuario_rol', 'usuario_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('usuario_rol', 'rol_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.drop_index('idx_usuario_rol_rol', table_name='usuario_rol')
    op.drop_index('idx_usuario_rol_usuario', table_name='usuario_rol')
    op.drop_constraint('uq_usuario_rol', 'usuario_rol', type_='unique')
    op.drop_table_comment(
        'usuario_rol',
        existing_comment='Relación entre usuarios y roles.',
        schema=None
    )
    op.drop_column('usuario_rol', 'updated_at')
    op.drop_column('usuario_rol', 'created_at')
    op.drop_index('idx_venta_cliente', table_name='venta')
    op.drop_index('idx_venta_estado', table_name='venta')
    op.drop_index('idx_venta_moneda', table_name='venta')
    op.create_index(op.f('ix_venta_id'), 'venta', ['id'], unique=False)
    op.drop_table_comment(
        'venta',
        existing_comment='Formalización de la entrega y facturación vinculada a un pedido.',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'venta',
        'Formalización de la entrega y facturación vinculada a un pedido.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_venta_id'), table_name='venta')
    op.create_index('idx_venta_moneda', 'venta', ['moneda_id'], unique=False)
    op.create_index('idx_venta_estado', 'venta', ['estado'], unique=False)
    op.create_index('idx_venta_cliente', 'venta', ['cliente_id'], unique=False)
    op.add_column('usuario_rol', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('usuario_rol', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_table_comment(
        'usuario_rol',
        'Relación entre usuarios y roles.',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint('uq_usuario_rol', 'usuario_rol', ['usuario_id', 'rol_id'])
    op.create_index('idx_usuario_rol_usuario', 'usuario_rol', ['usuario_id'], unique=False)
    op.create_index('idx_usuario_rol_rol', 'usuario_rol', ['rol_id'], unique=False)
    op.alter_column('usuario_rol', 'rol_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('usuario_rol', 'usuario_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('usuario_rol', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'usuario',
        'Usuarios que acceden al sistema.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('fk_usuario_empleado', 'usuario', 'empleado', ['empleado_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_usuario_nombre_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.create_unique_constraint('usuario_nombre_usuario_key', 'usuario', ['nombre_usuario'])
    op.create_unique_constraint('usuario_empleado_id_key', 'usuario', ['empleado_id'])
    op.create_index('idx_usuario_empleado', 'usuario', ['empleado_id'], unique=False)
    op.alter_column('usuario', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('usuario', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('usuario', 'empleado_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('usuario', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('usuario_id_seq'::regclass)"))
    op.create_table_comment(
        'unidad_medida',
        'Unidades de medida para los materiales e insumos.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_unidad_medida_id'), table_name='unidad_medida')
    op.create_unique_constraint('unidad_medida_nombre_key', 'unidad_medida', ['nombre'])
    op.create_table_comment(
        'ubicacion',
        'Ubicaciones físicas para almacenar inventario.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_ubicacion_id'), table_name='ubicacion')
    op.create_unique_constraint('ubicacion_nombre_key', 'ubicacion', ['nombre'])
    op.create_table_comment(
        'tipo_producto',
        'Clasificación principal de los productos.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_tipo_producto_id'), table_name='tipo_producto')
    op.create_unique_constraint('tipo_producto_nombre_key', 'tipo_producto', ['nombre'])
    op.create_table_comment(
        'tipo_gasto',
        'Categorización de los gastos operativos.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_tipo_gasto_id'), table_name='tipo_gasto')
    op.create_table_comment(
        'tasa_cambio',
        'Histórico de tasas de conversión.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_tasa_cambio_id'), table_name='tasa_cambio')
    op.create_unique_constraint('tasa_cambio_moneda_origen_id_moneda_destino_id_fecha_key', 'tasa_cambio', ['moneda_origen_id', 'moneda_destino_id', 'fecha'])
    op.create_index('idx_tasa_cambio_origen', 'tasa_cambio', ['moneda_origen_id'], unique=False)
    op.create_index('idx_tasa_cambio_destino', 'tasa_cambio', ['moneda_destino_id'], unique=False)
    op.alter_column('tasa_cambio', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'rol',
        'Roles del sistema para control de acceso.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_rol_id'), table_name='rol')
    op.create_unique_constraint('rol_nombre_key', 'rol', ['nombre'])
    op.create_table_comment(
        'proveedor',
        'Entidades que proveen materiales.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_proveedor_id'), table_name='proveedor')
    op.create_table_comment(
        'producto_material',
        'Receta paramétrica: relaciona cada producto con sus materiales y define cómo escala la cantidad cuando cambian las dimensiones.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_producto_material_id'), table_name='producto_material')
    op.create_index('idx_pm_producto', 'producto_material', ['producto_id'], unique=False)
    op.create_index('idx_pm_material', 'producto_material', ['material_id'], unique=False)
    op.alter_column('producto_material', 'rangos',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON para POR_RANGO: [{"max":1.8,"cantidad":2},{"max":2.2,"cantidad":4}].',
               existing_nullable=True)
    op.alter_column('producto_material', 'condicion_activacion',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON: {"campo":"nuevo_largo","op":">","valor":2.0}. Si no se cumple, la cantidad se fuerza a 0.',
               existing_nullable=True)
    op.alter_column('producto_material', 'tipo_escala',
               existing_type=sa.VARCHAR(length=20),
               comment='FIJO=no cambia | LINEAL=escala con largo | AREA=escala con área | ESPACIADO=perímetro/pauta | POR_RANGO=saltos discretos | FORMULA=expresión personalizada',
               existing_nullable=False)
    op.create_table_comment(
        'producto',
        'Catálogo de artículos base.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'producto', type_='foreignkey')
    op.create_foreign_key('producto_tipo_producto_id_fkey', 'producto', 'tipo_producto', ['tipo_producto_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_producto_id'), table_name='producto')
    op.create_unique_constraint('producto_codigo_key', 'producto', ['codigo'])
    op.create_index('idx_producto_tipo', 'producto', ['tipo_producto_id'], unique=False)
    op.alter_column('producto', 'alto_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Alto de referencia para calcular escalado (metros), opcional.',
               existing_nullable=True,
               existing_server_default=sa.text('NULL::numeric'))
    op.alter_column('producto', 'largo_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Largo de referencia para calcular escalado (metros).',
               existing_nullable=True,
               existing_server_default=sa.text('1.90'))
    op.alter_column('producto', 'ancho_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Ancho de referencia para calcular escalado (metros).',
               existing_nullable=True,
               existing_server_default=sa.text('1.60'))
    op.create_table_comment(
        'pedido',
        'Solicitud en firme aceptada por el cliente.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.create_foreign_key('pedido_cliente_id_fkey', 'pedido', 'cliente', ['cliente_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('pedido_cotizacion_id_fkey', 'pedido', 'cotizacion', ['cotizacion_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_pedido_id'), table_name='pedido')
    op.create_index('idx_pedido_estado', 'pedido', ['estado'], unique=False)
    op.create_index('idx_pedido_cliente', 'pedido', ['cliente_id'], unique=False)
    op.create_table_comment(
        'pago',
        'Abonos y pagos de ventas.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_pago_id'), table_name='pago')
    op.create_index('idx_pago_venta', 'pago', ['venta_id'], unique=False)
    op.create_index('idx_pago_moneda', 'pago', ['moneda_id'], unique=False)
    op.create_index('idx_pago_fecha', 'pago', ['fecha'], unique=False)
    op.create_table_comment(
        'orden_produccion',
        'Orden fabricada por detalle específico de pedido.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'orden_produccion', type_='foreignkey')
    op.create_foreign_key('orden_produccion_detalle_pedido_id_fkey', 'orden_produccion', 'detalle_pedido', ['detalle_pedido_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_orden_produccion_id'), table_name='orden_produccion')
    op.create_index('idx_orden_produccion_estado', 'orden_produccion', ['estado'], unique=False)
    op.create_table_comment(
        'movimiento_inventario',
        'Kardex/Historial de entradas y salidas.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_movimiento_inventario_id'), table_name='movimiento_inventario')
    op.create_index('idx_movimiento_ubicacion', 'movimiento_inventario', ['ubicacion_id'], unique=False)
    op.create_index('idx_movimiento_material', 'movimiento_inventario', ['material_id'], unique=False)
    op.create_index('idx_movimiento_fecha', 'movimiento_inventario', ['fecha'], unique=False)
    op.alter_column('movimiento_inventario', 'fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('movimiento_inventario', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'moneda',
        'Catálogo de monedas (COP, USD, VES).',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_moneda_id'), table_name='moneda')
    op.create_unique_constraint('moneda_nombre_key', 'moneda', ['nombre'])
    op.create_unique_constraint('moneda_codigo_key', 'moneda', ['codigo'])
    op.create_table_comment(
        'material',
        'Materia prima e insumos.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'material', type_='foreignkey')
    op.create_foreign_key('material_unidad_medida_id_fkey', 'material', 'unidad_medida', ['unidad_medida_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_material_id'), table_name='material')
    op.create_index('idx_material_unidad', 'material', ['unidad_medida_id'], unique=False)
    op.create_table_comment(
        'mano_obra',
        'Costos directos por labor de un empleado.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'mano_obra', type_='foreignkey')
    op.create_foreign_key('mano_obra_empleado_id_fkey', 'mano_obra', 'empleado', ['empleado_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_mano_obra_id'), table_name='mano_obra')
    op.create_index('idx_mano_obra_etapa', 'mano_obra', ['etapa_produccion_id'], unique=False)
    op.create_index('idx_mano_obra_empleado', 'mano_obra', ['empleado_id'], unique=False)
    op.create_table_comment(
        'inventario',
        'Existencias actuales por ubicación.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_inventario_id'), table_name='inventario')
    op.create_unique_constraint('inventario_material_id_ubicacion_id_key', 'inventario', ['material_id', 'ubicacion_id'])
    op.create_index('idx_inventario_ubicacion', 'inventario', ['ubicacion_id'], unique=False)
    op.create_index('idx_inventario_material', 'inventario', ['material_id'], unique=False)
    op.alter_column('inventario', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'gasto',
        'Registro de egresos operativos.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_gasto_id'), table_name='gasto')
    op.create_index('idx_gasto_tipo', 'gasto', ['tipo_gasto_id'], unique=False)
    op.create_index('idx_gasto_moneda', 'gasto', ['moneda_id'], unique=False)
    op.alter_column('gasto', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'etapa_produccion',
        'Seguimiento por áreas y encargados de producción.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'etapa_produccion', type_='foreignkey')
    op.drop_constraint(None, 'etapa_produccion', type_='foreignkey')
    op.create_foreign_key('etapa_produccion_area_id_fkey', 'etapa_produccion', 'area', ['area_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('etapa_produccion_empleado_responsable_id_fkey', 'etapa_produccion', 'empleado', ['empleado_responsable_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_etapa_produccion_id'), table_name='etapa_produccion')
    op.create_index('idx_etapa_orden', 'etapa_produccion', ['orden_produccion_id'], unique=False)
    op.create_index('idx_etapa_estado', 'etapa_produccion', ['estado'], unique=False)
    op.create_index('idx_etapa_empleado', 'etapa_produccion', ['empleado_responsable_id'], unique=False)
    op.create_index('idx_etapa_area', 'etapa_produccion', ['area_id'], unique=False)
    op.drop_index(op.f('ix_envio_id'), table_name='envio')
    op.create_table_comment(
        'empleado',
        'Personal de la empresa.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'empleado', type_='foreignkey')
    op.create_foreign_key('empleado_cargo_id_fkey', 'empleado', 'cargo', ['cargo_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_empleado_id'), table_name='empleado')
    op.create_index('idx_empleado_cargo', 'empleado', ['cargo_id'], unique=False)
    op.create_table_comment(
        'detalle_venta',
        'Líneas de los productos en la venta.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_detalle_venta_id'), table_name='detalle_venta')
    op.create_index('idx_detalle_venta_venta', 'detalle_venta', ['venta_id'], unique=False)
    op.create_index('idx_detalle_venta_producto', 'detalle_venta', ['producto_id'], unique=False)
    op.create_table_comment(
        'detalle_pedido',
        'Renglones del pedido con configuración personalizada.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'detalle_pedido', type_='foreignkey')
    op.create_foreign_key('detalle_pedido_producto_id_fkey', 'detalle_pedido', 'producto', ['producto_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_detalle_pedido_id'), table_name='detalle_pedido')
    op.create_index('idx_detalle_pedido_producto', 'detalle_pedido', ['producto_id'], unique=False)
    op.create_index('idx_detalle_pedido_pedido', 'detalle_pedido', ['pedido_id'], unique=False)
    op.create_table_comment(
        'detalle_compra',
        'Renglones de materiales adquiridos.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'detalle_compra', type_='foreignkey')
    op.create_foreign_key('detalle_compra_material_id_fkey', 'detalle_compra', 'material', ['material_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_detalle_compra_id'), table_name='detalle_compra')
    op.create_index('idx_detalle_compra_material', 'detalle_compra', ['material_id'], unique=False)
    op.create_index('idx_detalle_compra_compra', 'detalle_compra', ['compra_id'], unique=False)
    op.create_table_comment(
        'cotizacion',
        'Propuesta económica entregada al cliente.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'cotizacion', type_='foreignkey')
    op.create_foreign_key('cotizacion_cliente_id_fkey', 'cotizacion', 'cliente', ['cliente_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_cotizacion_id'), table_name='cotizacion')
    op.create_index('idx_cotizacion_cliente', 'cotizacion', ['cliente_id'], unique=False)
    op.create_table_comment(
        'costo_produccion',
        'Consolidado financiero del costo de manufactura.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_costo_produccion_id'), table_name='costo_produccion')
    op.create_table_comment(
        'consumo_material',
        'Descarga de materiales vinculados a una etapa.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'consumo_material', type_='foreignkey')
    op.create_foreign_key('consumo_material_material_id_fkey', 'consumo_material', 'material', ['material_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_consumo_material_id'), table_name='consumo_material')
    op.create_index('idx_consumo_material_fk', 'consumo_material', ['material_id'], unique=False)
    op.create_index('idx_consumo_etapa', 'consumo_material', ['etapa_produccion_id'], unique=False)
    op.create_table_comment(
        'compra',
        'Abastecimiento con proveedores.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'compra', type_='foreignkey')
    op.drop_constraint(None, 'compra', type_='foreignkey')
    op.create_foreign_key('compra_proveedor_id_fkey', 'compra', 'proveedor', ['proveedor_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('compra_moneda_id_fkey', 'compra', 'moneda', ['moneda_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_compra_id'), table_name='compra')
    op.create_index('idx_compra_proveedor', 'compra', ['proveedor_id'], unique=False)
    op.create_index('idx_compra_moneda', 'compra', ['moneda_id'], unique=False)
    op.create_table_comment(
        'cliente',
        'Registro de clientes.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.alter_column('cliente', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('cliente_id_seq'::regclass)"))
    op.create_table_comment(
        'cargo',
        'Cargos ocupados por los empleados.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_cargo_id'), table_name='cargo')
    op.create_unique_constraint('cargo_nombre_key', 'cargo', ['nombre'])
    op.create_table_comment(
        'area',
        'Áreas físicas o lógicas de producción.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_area_id'), table_name='area')
    op.create_unique_constraint('area_nombre_key', 'area', ['nombre'])
    op.create_table('cotizacion_material_ajuste',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('cotizacion_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('producto_material_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ancho_usado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('largo_usado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('cantidad_calculada', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('cantidad_ajustada', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizacion.id'], name='cotizacion_material_ajuste_cotizacion_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_material_id'], ['producto_material.id'], name='cotizacion_material_ajuste_producto_material_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cotizacion_material_ajuste_pkey'),
    comment='Guarda los ajustes manuales que hace el usuario sobre la lista de materiales calculada. Permite aprendizaje futuro.'
    )
    op.drop_index(op.f('ix_politica_seccion_id'), table_name='politica_seccion')
    op.drop_table('politica_seccion')
    op.drop_index(op.f('ix_elemento_seccion_seccion_id'), table_name='elemento_seccion')
    op.drop_index(op.f('ix_elemento_seccion_id'), table_name='elemento_seccion')
    op.drop_table('elemento_seccion')
    op.drop_index(op.f('ix_seccion_producto_producto_id'), table_name='seccion_producto')
    op.drop_index(op.f('ix_seccion_producto_id'), table_name='seccion_producto')
    op.drop_table('seccion_producto')
    # ### end Alembic commands ###
