"""telefono_not_null_in_cliente

Revision ID: f346bfe982db
Revises: 1068f2fa6502
Create Date: 2026-07-25 16:01:53.037614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f346bfe982db'
down_revision: Union[str, None] = '1068f2fa6502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Rellenar posibles filas con telefono NULL antes de aplicar NOT NULL
    op.execute("UPDATE cliente SET telefono = 'Sin teléfono' WHERE telefono IS NULL")
    op.alter_column('cliente', 'telefono',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'telefono',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
